name: spanet

channels:
  - pytorch
  - nvidia/label/cuda-11.8.0
  - conda-forge
  - nodefaults

dependencies:
  - python=3.10.*
  - conda
  - pip
  - cuda-toolkit

  - numpy=1.24
  - sympy
  - scikit-learn
  - numba
  - opt_einsum
  - h5py
  - cytoolz

  - pytorch=2.0.1
  - pytorch-lightning=2.0.7
  - pytorch-cuda=11.8
  - torchvision
  - torchaudio

  - tensorboard
  - tensorboardx

  - jupyterlab
  - seaborn
  - rich
